### ISSUE TITLE
How can I sign_up or create user as a User ?

### ISSUE THREAD

**Issue by dipto0321** [SotoArmando/MMembersOnly#6]
There should be a way for the user to registration from UI. SO please add this feature in this application.

**Comment by Ispirett** [comment]
Create a couple of users to populate your app with. We won’t be building a sign up form, so you’ll need to create new users via the command line. Your #before_create should now properly give each newly created user a special token.

**Comment by Ispirett** [comment]
We could not have built it but the app didn't say it needed to be done neither did microverse. Also I left some seed data ` rake db:seed`

**Comment by dipto0321** [comment]
HI @Ispirett ,
Yeah, I understand. But think about the real application. If this is your real application and I am the user. Then how come I created my account in your app. I know that it's not in the Odin guideline also not in microverse. But just think about it as a real app. What you will do if you are a real user want to use your own app for blog posting? Or you want to share it with your friends for fun 🙂 . Anyway, It's up to you.

**Comment by dipto0321** [comment]
Done
